sul_de_minas =['Aiuruoca', 'Alagoa', 'Albertina', 'Alfenas' , 'lpinopolis',
'Alterosa','Andradas','Andrelandia','Arantina','Arceburgo','Areado','Baependi',
'Bandeira do Sul','Boa Esperança','Bocaina de Minas','Bom Jardim de Minas',
'Bom Jesus da Penha','Bom Repouso','Borda da Mata','Botelhos','Brasopolis',
'Bueno Brandao','Cabo Verde','Cachoeira de Minas','Caldas','Camanducaia',
'Cambui','Cambuquira','Campanha','Campestre','Campo do Meio','Campos Gerais',
'Capetinga','Capitolio','Careacu','Carmo da Cachoeira','Carmo de Minas',
'Carmo do Rio Claro','Carrancas','Carvalhopolis','Carvalhos','Cassia',
'Caxambu','Claraval','Conceicao da Aparecida','Conceicao das Pedras',
'Conceicao do Rio Verde','Conceicao dos Ouros','Congonhal','Consolacao',
'Coqueiral','Cordislandia','Corrego do Bom Jesus','Cristina','Cruzilia',
'Delfim Moreira','Delfinopolis','Divisa Nova','Dom Vicoso','Eloi Mendes',
'Espirito Santo do Dourado','Estiva','Extrema','Fama','Fortaleza de Minas',
'Goncalves','Guape','Guaranesia','Guaxupe','Heliodora','Ibiraci',
'Ibitiura de Minas','Ijaci','Ilicinea','Inconfidentes','Ingai','Ipuiuna',
'Itajuba','Itamoji','Itamonte','Itanhandu','Itapeva','Itau de Minas',
'Itumirim','Itutinga','Jacui','Jacutinga','Jesuania','Juruaia','Lambari',
'Lavras','Liberdade','Luminarias','Machado','Maria da Fe','Marmelopolis',
'Minduri','Monsenhor Paulo','Monte Belo','Monte Santo de Minas','Monte Siao',
'Munhoz','Muzambinho','Natercia','Nepomuceno','Nova Resende','Olimpio Noronha',
'Ouro Fino','Paraguacu','Paraisopolis','Passa Quatro','Passa Vinte','Passos',
'Pedralva','Pirangucu','Piranguinho','Poco Fundo','Pocos de Caldas',
'Pouso Alegre','Pouso Alto','Pratapolis','Ribeirao Vermelho',
'Santa Rita de Caldas','Santa Rita do Sapucai','Santana da Vargem',
'Sao Bento Abade','Sao Goncalo do Sapucai','Sao Joao Batista do Gloria',
'São Joao da Mata','Sao Jose da Barra','Sao Jose do Alegre','Sao Lourenco',
'Sao Pedro da Uniao','Sao Sebastiao da Bela Vista','Sao Sebastiao do Paraiso',
'Sao Sebastiao do Rio Verde','Sao Tomas de Aquino','Sao Tome das Letras',
'Sao Vicente de Minas','Sapucai Mirim','Senador Amaral','Senador Jose Bento',
'Seritinga','Serrania','Serranos','Silvianopolis','Soledade de Minas',
'Tocos do Moji','Toledo','Tres Coracoes','Tres Pontas','Turvolandia',
'Varginha','Venceslau Bras','Virginia']